-- New random products data
INSERT INTO "products" ("name", "tagline", "description", "how_it_works", "icon", "url", "profile_id", "category_id") VALUES
('DataViz', 'Data visualization made simple', 'Transform complex data into clear, actionable insights.', 'Uses advanced algorithms to automatically generate beautiful and informative visualizations from raw data.', 'https://example.com/dataviz.png', 'https://dataviz.app', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 5),
('SecureChat', 'End-to-end encrypted messaging platform', 'Communication with uncompromising privacy and security.', 'Implements military-grade encryption protocols to ensure that only intended recipients can access message content.', 'https://example.com/securechat.png', 'https://securechat.io', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 1),
('FitnessPro', 'Personalized workout companion', 'Achieve your fitness goals with customized training plans.', 'Uses machine learning to adapt workout routines based on user performance, preferences, and progress.', 'https://example.com/fitnesspro.png', 'https://fitnesspro.fit', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 2),
('CodeReview', 'Automated code quality checker', 'Improve code quality and catch bugs before they reach production.', 'Analyzes code patterns to identify potential issues, security vulnerabilities, and performance bottlenecks.', 'https://example.com/codereview.png', 'https://codereview.dev', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 4),
('MealPlanner', 'Smart nutrition and meal planning', 'Plan healthy, balanced meals tailored to your dietary needs.', 'Combines nutritional science with AI to generate personalized meal plans that match dietary restrictions and health goals.', 'https://example.com/mealplanner.png', 'https://mealplanner.health', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 2),
('VoiceScript', 'Speech-to-text transcription service', 'Convert spoken words to accurate text in seconds.', 'Employs advanced speech recognition models trained on diverse accents and speaking styles for maximum accuracy.', 'https://example.com/voicescript.png', 'https://voicescript.ai', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 3),
('ProjectSync', 'Project management and team collaboration tool', 'Keep your team aligned and projects on track.', 'Integrates task management, document sharing, and communication in a unified workspace with real-time synchronization.', 'https://example.com/projectsync.png', 'https://projectsync.work', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 1),
('UXPrototype', 'Rapid UI/UX prototyping tool', 'Design and test user interfaces without coding.', 'Provides drag-and-drop components and interactive elements that can be quickly assembled into functional prototypes.', 'https://example.com/uxprototype.png', 'https://uxprototype.design', '2829c905-1254-4b8f-91eb-97cf99e86dcd', 5); 